import tkinter as tk
from tkinter import messagebox
import random
from PIL import Image, ImageTk

# Sample jokes database
# Template for 100 jokes
jokes = [
    {"id": 1, "joke": "Were they really on about a mouse inside that random Mexican restaurant? *points at McDonalds*", "explanation": "McDonalds is not really a mexican place although mexican can work there giving a falsetto vibe. UCSD theory: incongruity and superiority"},
    {"id": 2, "joke": "When someone stops doing weed after being high a long time they gain superpowers: no longer need to sleep or eat. For a while at least", "explanation": "Those arent really super powers. UCSD theory: Incongruity theory and Reversal theory "},
    {"id": 3, "joke": "First World Problems: I need to go to the bathroom again because I ate to many ribs!", "explanation": "UCSD theory: inconruity Theory, Reversal Theory "},
    {"id": 4, "joke": "First World Problems: All my cloths are wet... from working out... for no reason", "explanation": "they are lifting black items aka weights in the gym for no practical purpose"},
    {"id": 5, "joke": "It was runored that Covid-19 was cause by drinking bat piss. breaking news from wuhan china: we drank the piss... alledgedly", "explanation": "they need a coke"},
    {"id": 6, "joke": "That woman is 3/4 Saddam Hussein", "explanation": "thats incest"},
    {"id": 7, "joke": "In hell there is an astrix where it says - or take the UCSD finals. and NO ONE chooses it because the UCSD final are worse than hell", "explanation": "...that's true, I've seen that sign in there"},
    {"id": 8, "joke": "The research topic of how to harness the snitch: is a semi real superpower. people just run up to you TRYING to tell you some dirt", "explanation": "TBD"},
    {"id": 9, "joke": "...the only thing I'm attracted to anymore are girls in full bankai", "explanation": "realistically... I'm going to have to settle for less"},
    {"id": 10, "joke": "You guys been sayin sus?", "explanation": "...i know what its like to not say it"},
    {"id": 11, "joke": "Blender the computer program x food joke: whenever in life someone say 'open blender' i guess things are going pretty good", "explanation": "mmm jamba juice... mmmm"},
    {"id": 12, "joke": "From shrek. I want to be like donkey, because no one has ever come up so much to be a donkey fucking a huge fire breathing dragon", "explanation": "TBD"},
    {"id": 13, "joke": "Its so hot I started sweating from reading at 9:30 am", "explanation": "TBD"},
    {"id": 14, "joke": "What kind of accent do you have? an adult swim accent", "explanation": "TBD"},
    {"id": 15, "joke": "Added cheese 'the american way' *evil laugh* MORE! MORE! muahaha", "explanation": "TBD"},
    {"id": 16, "joke": "Cheese is the only food that can cause white people to stop being hungry", "explanation": "TBD"},
    {"id": 17, "joke": "New worst insult to freckles people: 'omfg is your face covers in flees", "explanation": "TBD"},
    {"id": 18, "joke": "Umm.. what is the correct gem stoen ring to give to your GF to have a polygamy relationship?", "explanation": "TBD"},
    {"id": 19, "joke": "Some says that is 'male gaze', I'm like nah thats male straights!", "explanation": "TBD"},
    {"id": 20, "joke": "Dyslexia: *clears throat* 'lex luthor is a fag' ...'you are cured'", "explanation": "TBD"},
    {"id": 21, "joke": "*alert* all registers are down at target 'god dam skynet has been stopped'", "explanation": "TBD"},
    {"id": 22, "joke": "The visual arts studio at UCSD is surrounded by jurrassic park style defense. WTF is in there?", "explanation": "TBD"},
    {"id": 23, "joke": "20 million dollars to find out what happened to me! ...it was nothing", "explanation": "TBD"},
    {"id": 24, "joke": "Best tyoe of aids ...maids", "explanation": "that is true"},
    {"id": 25, "joke": "They say 'stop brinking coke because it is bad for you' NO! you tell cokes to change!", "explanation": "TBD"},
    {"id": 26, "joke": "Free Palestine! '...maybe they will stop if you say is has more than 0 value'", "explanation": "TBD"},
    {"id": 27, "joke": "low chairaphanalia. def: no place to sit", "explanation": "TBD"},
    {"id": 28, "joke": "We go to ask the computer 'what will i die from'. it says 'cancer'. she makes the face -_-. the computer suddenly recalculates and says 'hepatitis, aids and minor friction burns'", "explanation": ":D"},
    {"id": 29, "joke": "Cloths let fat people get away with being fat", "explanation": "TBD"},
    {"id": 30, "joke": "Warning: that is a karen in the dormant phase", "explanation": "TBD"},
    {"id": 31, "joke": "Hasbula save palestine", "explanation": "TBD"},
    {"id": 32, "joke": "My password make them say 'I consent to everything with matt' when they type it in", "explanation": "TBD"},
    {"id": 33, "joke": "The Ai tool: anus detailer. I forgot how completely nessesary that is", "explanation": "TBD"},
    {"id": 34, "joke": "Bomb sniffing pomeranian, basically super under-cover dog", "explanation": "TBD"},
    {"id": 35, "joke": "It seems like I have gained a few pounds of 'you know what' ....it's pubes. GOOD NEWS! she eats pubes! 'oh my god finally'", "explanation": "TBD"},
    {"id": 36, "joke": "Bomb threat? '...its probably in my neck and I dont even know about it'", "explanation": "TBD"},
    {"id": 37, "joke": "It's not my fault I am from the weed prohibition era", "explanation": "TBD"},
    {"id": 38, "joke": "18 wheeler joke: 'who brought this mexican buss'", "explanation": "TBD"},
    {"id": 39, "joke": "When I wrote this I was looking for 'Advance Computational Intelligence for Dummy's", "explanation": "TBD"},
    {"id": 40, "joke": "Why did the pizza end up in the oven? It was a feminist trying to get out of the kitchen, by any means possible", "explanation": "TBD"},
    {"id": 41, "joke": "Mexican food Capitalism evolution is crazy in san diego. If the food is bad at all we will go next door and they will close", "explanation": "TBD"},
    {"id": 42, "joke": "Your parent is only hot because you are great", "explanation": "TBD"},
    {"id": 43, "joke": "A new study revealed that when whales beach themself on land. it is because they are trying to get out of UCSD test anxiety", "explanation": "TBD"},
    {"id": 44, "joke": "First Sign of the Rise of the Machines: Malfunctioning auto toilet", "explanation": "TBD"},
    {"id": 45, "joke": "Mouse satan, aka the human who experiment on mouse. write the hardest test of all time", "explanation": "TBD"},
    {"id": 46, "joke": "Jesus would ask to get nailed back to the cross from the stres of UCSD. he will say 'PUT ME BACK!'", "explanation": "Benine Violation Theory, Incongruity theory, Reversal theory"},
    {"id": 47, "joke": "Team Name: 'You didn't do a good job' ...yea ...thats their team name", "explanation": "TBD"},
    {"id": 48, "joke": "Elevatoriouse, the prison", "explanation": "stuck in a evlevator at the wrong time is pretty bad"},
    {"id": 49, "joke": "Mexican accent: 'jeck' -> check", "explanation": "TBD"},
    {"id": 50, "joke": "Cunnalingus fish?  ...its cuttle fish! ...ohhhh", "explanation": "TBD"},
    {"id": 51, "joke": "With all the clout of UCSD, it still gets a dirty bathroom...", "explanation": "TBD"},
    {"id": 52, "joke": "Ancient humans say 'east side' then leaves africa", "explanation": "TBD"},
    {"id": 53, "joke": "Anyone who doesnt like it overcooks their meat! -_-   ...you bastard!", "explanation": "TBD"},
    {"id": 54, "joke": "That is not a spliff!!  ...it only has weed...", "explanation": "TBD"},
    {"id": 55, "joke": "Reading Hamlet. ...is that about a pig or something", "explanation": "TBD"},
    {"id": 56, "joke": "Extremely loose academic integrity rules like: 'did they have guns?'  ...no? NOT CHEATING! ", "explanation": "TBD"},
    {"id": 57, "joke": "This is the best laptop... for doing cocaine!", "explanation": "Incongruity Theory, Reversal Theory"},
    {"id": 58, "joke": "Did you want any? ...well it doesnt mean you can have it, I'm just checking", "explanation": "TBD"},
    {"id": 59, "joke": "In the name of all white people I hear by reclaim rice from the asians. We also like rice!", "explanation": "TBD"},
    {"id": 60, "joke": "69 is gay, it should be 68 or 89. People are stupud for that", "explanation": "TBD "},
    {"id": 61, "joke": "lofi means low finance, its bad, stop labeling yourself something bad", "explanation": "TBD"},
    {"id": 62, "joke": "Karate flop into the bed. The only reason the earth was saved was becasue the bed was there", "explanation": "TBD"},
    {"id": 63, "joke": "*Demonstraits how to escape after putting fired chicken into the chocolate fountain*", "explanation": "TBD"},
    {"id": 64, "joke": "It says that is holy ground, it sounds dangerouse, it may break your ancles", "explanation": "TBD"},
    {"id": 65, "joke": "If chick-fil-a is chicken, then what is panda express... ", "explanation": "TBD"},
    {"id": 66, "joke": "There is basically poo everywhere... at a medical level", "explanation": "TBD"},
    {"id": 67, "joke": "Its open horse AI", "explanation": "source"},
    {"id": 68, "joke": "Why does the last french fry taste so bad?", "explanation": "TBD"},
    {"id": 69, "joke": "Hollowed out books are becoming a more safe place to hide things", "explanation": "TBD"},
    {"id": 70, "joke": "Is Gary from one piece?", "explanation": "...no"},
    {"id": 71, "joke": "She says 'im nervouse' reply 'thats just my spirit pressure, reiatsu'", "explanation": "TBD"},
    {"id": 72, "joke": "I ride the trolly so you basically need an air born immune boost to go near me", "explanation": "TBD"},
    {"id": 73, "joke": "The monk on instagram says' never give up' ...wtf does he know?", "explanation": "TBD"},
    {"id": 74, "joke": "After the 5th booster shot it is possible to become addicted to the corona virus vaccine", "explanation": "TBD"},
    {"id": 75, "joke": "Seth Rogan Style: Bring open drink into the restroom and through the whole process be taking sips", "explanation": "similar to open container driving"},
    {"id": 76, "joke": "Toyota Highlander: There can be only one!", "explanation": "TBD"},
    {"id": 77, "joke": "Thats whore-able not horrible", "explanation": "TBD"},
    {"id": 78, "joke": "This is pretty much how I party *drinks from the milk gallon in the fridge*   ...now you know", "explanation": "TBD"},
    {"id": 79, "joke": "Free sandwhich? for how long?   ...free sandwhich for ONCE!", "explanation": "TBD"},
    {"id": 80, "joke": "Food is the reagent for poop ...its a poop joke", "explanation": "TBD"},
    {"id": 81, "joke": "Fake japanses: 'ho-die' family surname", "explanation": "TBD"},
    {"id": 82, "joke": "Why do you like your school? Well its not from the parking", "explanation": "TBD"},
    {"id": 83, "joke": "Stressed is deserts backwards", "explanation": "TBD"},
    {"id": 84, "joke": "Being sore from workout when everyone else is fat", "explanation": "TBD"},
    {"id": 85, "joke": "We really need to stop age and live forever so we can all just keep playing world of warcraft", "explanation": "TBD"},
    {"id": 86, "joke": "Harnes the homeless", "explanation": "TBD"},
    {"id": 87, "joke": "My role model for dating is my dog. He is a butt licker. ... with that in mind, I'm pretty sure that girl should have stayed.", "explanation": "TBD"},
    {"id": 88, "joke": "Why are all the pyramids abandonded? what a waste of time", "explanation": "TBD"},
    {"id": 89, "joke": "Why didn't anyone tell me i was the beast titan IRL", "explanation": "TBD"},
    {"id": 90, "joke": "The new anime has 11 boy characters and only 1 girl. Who sat there and drew 11 boys?", "explanation": "TBD"},
    {"id": 91, "joke": "The blue pill takes you to One Piece Land, the red pill takes you to Naruto Land", "explanation": "TBD"},
    {"id": 92, "joke": "Roomba is a bread theft! wtf cut its hands off!", "explanation": "it doesnt have hands"},
    {"id": 93, "joke": "I need to licked clean from all the sweating while doing VR work", "explanation": "TBD"},
    {"id": 94, "joke": "Run and run and run and workout and workout, then go to dennys ONCE and your are fat again", "explanation": "TBD"},
    {"id": 95, "joke": "It's a UFO!!! ...thats a to go box of pancakes... ", "explanation": "TBD"},
    {"id": 96, "joke": "We dont do butt stuff, we only do ass to mouth stuff", "explanation": "TBD"},
    {"id": 97, "joke": "Deamon nuns are not scarry, I'm abount to double dip poo into her vagina if she doesnt calm down", "explanation": "TBD"},
    {"id": 98, "joke": "If we give barrack obama a polygraph I want to ask if we can say the n-word just to see what the polygraph does.", "explanation": "TBD"},
    {"id": 99, "joke": "Hey looks its batman! no... it's the Jeepers Creepers monster. Dam thats way worse", "explanation": "TBD"},
    {"id": 100, "joke": "Worst kind of aids, financial aids", "explanation": "TBD"},
    {"id": 101, "joke": "gandalf whats to know what you mean by good morning... again. i said shut up its a command", "explanation": "incongruity theory, superiority theory"},
    {"id": 102, "joke": "*goes to aids support group* says 'i have financial aids, umm is this the right place?", "explanation": "TBD"},
    {"id": 103, "joke": "they said have a pig to get you out of everything. *yells back* what about when i am eating them will they getting me out of it? ok thanks LMK", "explanation": "TBD"},
    {"id": 104, "joke": "I'll get the insents, it really stinks in here, 'THATS WEED!' oh um dont check", "explanation": "TBD"},
    {"id": 105, "joke": "Ai like gpt has a hard time being correct about 'how ai works'", "explanation": "TBD"},
    {"id": 106, "joke": "There is a mosquito in here, im going to eat him this time", "explanation": "TBD"},
    {"id": 107, "joke": "How did the salse end up in the bathroom? well mainly... i was sober", "explanation": "TBD"},
    {"id": 108, "joke": "Somehow they crashed into the titanic", "explanation": "TBD"},
    {"id": 109, "joke": "You are pharmaceutically illiterate. ...dam i need to get my drugs somewhere", "explanation": "TBD"},
    {"id": 110, "joke": "Team Humans: the most evil and ruthless race of earth", "explanation": ""},
    {"id": 111, "joke": "Worst word: wifi dongle", "explanation": "TBD"},
    {"id": 112, "joke": "Worst word: leotard", "explanation": "TBD"},
    {"id": 113, "joke": "Worst word: resurrection", "explanation": "TBD"},
    {"id": 114, "joke": "Worst work: dictation", "explanation": "TBD"},
    {"id": 115, "joke": "People keep going into the resturant restroom and never comging out, are we eating them? Nah they only do that at olive garden", "explanation": "TBD"},
    {"id": 116, "joke": "Just saved your life from the dangerouse joke that was going to show up here ", "explanation": "TBD"},
    {"id": 117, "joke": "Neck beards only", "explanation": "TBD"},
    {"id": 118, "joke": "I named the workout machine immoble suit gundam", "explanation": "TBD"},
    {"id": 119, "joke": "The AI named wet says 'I'm wet'", "explanation": "TBD"},
    {"id": 120, "joke": "The fake titty drop didnt move and inch", "explanation": "TBD"},
    {"id": 121, "joke": "Scientist have recently harnessed the ability of the dog to do a no wipe clean poo", "explanation": "TBD"},
    {"id": 122, "joke": "You said it was 4080! bruh it says 480", "explanation": "TBD"},
    {"id": 123, "joke": "She took his facehit-ginity D': unconsentualllly", "explanation": "TBD"},
    {"id": 124, "joke": "Double UCSD anual funding! lol good luck", "explanation": "TBD"},
    {"id": 125, "joke": "Dont comp=plain only comp-advanced", "explanation": "TBD"},
    {"id": 126, "joke": "Liberal study is about how much butter to put", "explanation": "TBD"},
    {"id": 127, "joke": "The enemy of my enemy has no more enemies because I killed all their enemies because they were my friend", "explanation": "TBD"},
    {"id": 128, "joke": "I was going to 3D print myself a girlfriend... the technology is not where i need it to be", "explanation": "TBD"},
    {"id": 129, "joke": "Just agree UCSD is pretty cool to get to press the button again", "explanation": "TBD"},
    {"id": 130, "joke": "The missing emoji, the snot rocket emoji", "explanation": "TBD"},
    {"id": 131, "joke": "!!MIND CONTROL!! press again!", "explanation": "TBD"},
    {"id": 132, "joke": "Mongolians get called hun and no one realize what they are saying", "explanation": "TBD"},
    {"id": 133, "joke": "Oh man my castlevenia image generator was making fat chicks again", "explanation": "TBO"},
    {"id": 134, "joke": "Rich folk request to pay more at 7-11", "explanation": "TBD"},
    {"id": 135, "joke": "Gym Tan Lanundry years after the show was canceled", "explanation": "TBD"},
    {"id": 136, "joke": "Silly pigs bacons is for pigs", "explanation": "TBD"},
    {"id": 137, "joke": "You know who needs to die out? People quoting gandalf w/o propper credit", "explanation": "TBD"},
    {"id": 138, "joke": "Did you realize noone sells ants on a log", "explanation": "TBD"},
    {"id": 139, "joke": "I have chizzeled anchels", "explanation": "incongruity theory and superiority theory"},
    {"id": 140, "joke": "The whale killers died from the giant squid which is the whale natural food source", "explanation": "TBD"},
    {"id": 141, "joke": "Baby Jesus fell out of the manger. Dam it baby Jesus get back in bed!", "explanation": "TBD"},
    {"id": 142, "joke": "I was trying to turn in encrytped answers in school, they were not having it", "explanation": "TBD"},
    {"id": 143, "joke": "Trained orangutan: There he is again! pushing buttons expecting joke again huh?", "explanation": "TBD"},
    {"id": 144, "joke": "Back at the pad ...the iPad", "explanation": "incongruity theory"},
    {"id": 145, "joke": "Innapropriate brand", "explanation": "TBD"},
    {"id": 146, "joke": "Don't forget the silent letter in the new acronyms", "explanation": "TBD"},
    {"id": 147, "joke": "My neighbor tried to stop my local music and the butterfly effect caused russia to take over the world", "explanation": "TBD"},
    {"id": 148, "joke": "what house does house music come from? no one knows", "explanation": "TBD"},
    {"id": 149, "joke": "GPU smells from bad thermal paste", "explanation": "TBD"},
    {"id": 150, "joke": "Dont forget your cran. you know what happened? they forgot the cran", "explanation": "TBD"},
    {"id": 151, "joke": "Call of duty fish? ...cods?", "explanation": "TBD"},
    {"id": 152, "joke": "That traffic light was so long I got sober", "explanation": "TBD"},
    {"id": 153, "joke": "It claims there was a complete download. UNSUBSTANTIATE CLAIMS!", "explanation": "TBD"},
    {"id": 154, "joke": "Hacking the cold tub of butter. its thickk", "explanation": "good visual, extended cognitive schema, reverals theory ingongruity theory"},
    {"id": 155, "joke": "Nudist hacker trying to get caught", "explanation": "TBD"},
    {"id": 156, "joke": "Loss of bet leads to immediate double or nothing contest of who will order the best from DoorDash", "explanation": ""},
    {"id": 157, "joke": "Reserve a parking spot for the online class and never use it", "explanation": "TBD"},
    {"id": 158, "joke": "I tried to show some tetris as if it was new in 2023, they went for it", "explanation": "TBD"},
    {"id": 159, "joke": "Godslap was able to stop omni man", "explanation": "TBD"},
    {"id": 160, "joke": "South park is coming true again...", "explanation": "TBD"},
    {"id": 161, "joke": "The girls come naturally scented", "explanation": "TBD"},
    {"id": 162, "joke": "Sometimes code in ruby so the cpu will turn ruby red", "explanation": "TBD"},
    {"id": 163, "joke": "Tip the customer instead", "explanation": "TBD"},
    {"id": 164, "joke": "Embody your last halloween costume mid year", "explanation": "TBD"},
    {"id": 165, "joke": "Laugh-rican the tribe of the congo", "explanation": "TBD"},
    {"id": 166, "joke": "I was possesed by noot noot", "explanation": "TBD"},
    {"id": 167, "joke": "No one wants to pay me for doing situps", "explanation": "TBD"},
    {"id": 168, "joke": "What is marcell walics' name?", "explanation": "TBD"},
    {"id": 169, "joke": "White people often mistake hunger for the need for more cheese", "explanation": "TBD"},
    {"id": 170, "joke": "One way to make the world a better place: fight over who is the better gift giver", "explanation": "TBD"},
    {"id": 171, "joke": "No one likes the rules. '...its says no rules' yea.. none like that", "explanation": "TBD"},
    {"id": 172, "joke": "Extra strength cliche - clicheanus", "explanation": "TBD"},
    {"id": 173, "joke": "Why is one called date and the other g,rapes. The royal namer is fired again", "explanation": "TBD"},
    {"id": 174, "joke": "While being spied, in the bathroom, say 'what do you mean I get the most work done in here!?' ", "explanation": "TBD"},
    {"id": 175, "joke": "Nice place gets replaced by the worst mexican resturant", "explanation": "TBD"},
    {"id": 176, "joke": "Girl dogs let their owner say bitch", "explanation": "TBD"},
    {"id": 177, "joke": "Free refile should be legal law in California", "explanation": "TBD"},
    {"id": 178, "joke": "I've been born there all my life", "explanation": "TBD"},
    {"id": 179, "joke": "Only portrail mode monitors will be allowed", "explanation": "TBD"},
    {"id": 180, "joke": "I didnt have a PhD I have a PhA, I'm really good at acid base equations", "explanation": "TBD"},
    {"id": 181, "joke": "Boba Is made of pure evil", "explanation": "TBD"},
    {"id": 182, "joke": "The problem cup: a smaller coffee that is way to hot to drink, just end up holding it burning your hand and trying not to spill", "explanation": "TBD"},
    {"id": 183, "joke": "Sometime nostalgia from anime is so strong it can kill chinese people", "explanation": "TBD"},
    {"id": 184, "joke": "You've seen one punch man, so you know what its like in real life", "explanation": "TBD"},
    {"id": 185, "joke": "Some real grey areas: where to draw the link beteween trucker horn motion dance and fist pumping motion dance", "explanation": "TBD"},
    {"id": 186, "joke": "Our Ai will be friends, we wont even hand out", "explanation": "TBD"},
    {"id": 187, "joke": "Hacking is prison rules", "explanation": "TBD"},
    {"id": 188, "joke": "In the shinning the evevator opens and bloods fall out not liquid", "explanation": "TBD"},
    {"id": 189, "joke": "Oh geez they are going to check if valhalla is real again", "explanation": "TBD"},
    {"id": 190, "joke": "Extreme curse grade 1: cause all Ai to not be able to stop being cliche", "explanation": "TBD"},
    {"id": 191, "joke": "you have bet all the free things....", "explanation": "TBD"},
    {"id": 192, "joke": "They dont even know how stoned I am, they dont even check. They dont even care", "explanation": "TBD"},
    {"id": 193, "joke": "Medical marijuana leaf is not LLM its MML", "explanation": "TBD"},
    {"id": 194, "joke": "It was confirmed that skynet trained in starcraft 2", "explanation": "TBD"},
    {"id": 195, "joke": "Worst heros: Alexa Man - The power to control alexa", "explanation": "TBD"},
    {"id": 196, "joke": "Worst heros: Shazam Man - The power to ID all songs", "explanation": "TBD"},
    {"id": 197, "joke": "Worst heros: Notes man - wont forget after writes it down", "explanation": "TBD"},
    {"id": 198, "joke": "A club where the ONLY thing they talk about is weather or not they will hang out outside of the club. They choose no. but return to the club anyway", "explanation": "TBD"},
    {"id": 199, "joke": "Apple adds a day to the calender and no one notice", "explanation": "TBD"},
    {"id": 200, "joke": "Farming lizard tails because they grow back", "explanation": "TBD"},
    {"id": 200, "joke": "Do people not know that hearts look like butts?", "explanation": "TBD"},
    {"id": 201, "joke": "Didn't Dave Chappell kind of pave the way for barrak obama", "explanation": "TBD"},
    {"id": 202, "joke": "Suspicious? no supicithem", "explanation": "TBD"},
    {"id": 203, "joke": "Ridiculously low level bribes then demand 'is that good enough?!?!' example:1rolled taco", "explanation": "TBD"},
    {"id": 204, "joke": "I can't spell today... teday?", "explanation": "TBD"},
    {"id": 205, "joke": "FTD not DTF: fight to death not down to fuck", "explanation": "TBD"},
    {"id": 206, "joke": "If someone with regroth power is decapitated do the regrown the head or the body?", "explanation": "TBD"},
    {"id": 207, "joke": "Connect the human centipede into the shape of a circle", "explanation": "TBD"},
    {"id": 208, "joke": "Human centipede laxitive straws", "explanation": "TBD"},
    {"id": 209, "joke": "They softly whispered pancakes...", "explanation": "TBD"},
    {"id": 210, "joke": "At the carwash the black man says in shock: 'oh shit they baught the gold one they about to clean the shit outta that car'", "explanation": "TBD"},
    {"id": 211, "joke": "what if one day every guy woke up and his balls had little arms and they ALL said : 'geo-dude' *makes the face*", "explanation": "TBD"},
    {"id": 212, "joke": "I wish i went on TRL once in my life", "explanation": "TBD"},
    {"id": 213, "joke": "You guys are fucking on my smoke game", "explanation": "TBD"},
    {"id": 214, "joke": "You got any regular spoons, nah we only got weird spoons", "explanation": "TBD"},
    {"id": 215, "joke": "She said a herpis joke the second time i meet her, i can trust her", "explanation": "TBD"},
    {"id": 216, "joke": "Eat a cherry candy befpre a real cherry", "explanation": "TBD"},
    {"id": 217, "joke": "behold true fear! *release mosquito into the room*", "explanation": "TBD"},
    {"id": 218, "joke": "One the subway some really yells 'Im the you of prison rimjobs'", "explanation": "TBD"},
    {"id": 219, "joke": "Danny divito goes to petco high on LSD to find hickory smoked pill pocket: a way to hide drugs in food. This is so he can fulfill an ocult ritual. When he arrives he is to high on LSD and starts eating the pill pockets in the store, he trys to vomit to get the cashback.", "explanation": "TBD"},
    {"id": 220, "joke": "Good thing or bad thing:  I got it from the water that splash up when you poo", "explanation": "TBD"},
    {"id": 221, "joke": "Years old aged 5 hour energy drink is sold at auction", "explanation": "TBD"},
    {"id": 222, "joke": "Well you are only allowed to reproduce with people who have brazilian anal waxing", "explanation": "TBD"},
    {"id": 223, "joke": "When my dog was potty training I got flowerd leis for the terrible small", "explanation": "TBD"},
    {"id": 224, "joke": "George Bush lives in a giant hudge maze", "explanation": "TBD"},
    {"id": 225, "joke": "What do you think this is, A charity for midgets?", "explanation": "TBD"},
    {"id": 226, "joke": "Baby birds say cheep because they have low self esteme", "explanation": "TBD"},
    {"id": 227, "joke": "Mexican Bettlejuice. is real", "explanation": "TBD"},
    {"id": 228, "joke": "Spot bot liquid reuse purpose", "explanation": "TBD"},
    {"id": 229, "joke": "Repeatedly give namtive american gift that you bought at their own casino gift shop", "explanation": "TBD"},
    {"id": 230, "joke": "Big cat eats dog is opposite of cyote eats house cat.", "explanation": "TBD"},
    {"id": 231, "joke": "New puts out definition: give soup", "explanation": "TBD"},
    {"id": 232, "joke": "Only when he in smiling.. well better cut his lips off if you insist", "explanation": "TBD"},
    {"id": 233, "joke": "Open win and out near in and out", "explanation": "TBD"},
    {"id": 234, "joke": "Real superpower of warcraft: lays down man, at any terrible event just lays down for w while and has an out of body eperience", "explanation": "TBD"},
    {"id": 235, "joke": "Marriage contract requirment: The amount of required rimjobs to be given by someone else", "explanation": "TBD"},
    {"id": 236, "joke": "Don't say bull shit, say horse shit. trending", "explanation": "TBD"},
    {"id": 237, "joke": "Harmonized sounds of multiple spot bot cleaning units", "explanation": "TBD"},
    {"id": 238, "joke": "Little girl cscreams at the cliche of that one house who never does christmas lights", "explanation": "TBD"},
    {"id": 239, "joke": "Legally alowed to kill with anything christmas related", "explanation": "TBD"},
    {"id": 240, "joke": "Captain picard of star trek. Wear blue bandana around bald head and is a crip", "explanation": "TBD"},
    {"id": 241, "joke": "Are you recist against clones?", "explanation": "TBD"},
    {"id": 242, "joke": "You milk butt?", "explanation": "TBD"},
    {"id": 243, "joke": "Person with gun falls out of many hidden places. he just falls out with a gun like reaction tv", "explanation": "TBD"},
    {"id": 244, "joke": "Ominouse red oldschool desk phone stuff... thats it... thats what she was into", "explanation": "TBD"},
    {"id": 245, "joke": "Seriously bad phone tag about snakes wih long genetics name", "explanation": "TBD"},
    {"id": 246, "joke": "Creepy baby sounds", "explanation": "TBD"},
    {"id": 247, "joke": "I was training that dog to fart on command and you killed it", "explanation": "TBD"},
    {"id": 248, "joke": "Sound pad of tones selection: 'terrorist tones'", "explanation": "TBD"},
    {"id": 249, "joke": "Blind people cleaning windows", "explanation": "TBD"},
    {"id": 250, "joke": "Kai lo ren weilds a cross", "explanation": "TBD"},
    {"id": 251, "joke": "Video of meat flapping around near people working out", "explanation": "TBD"},
    {"id": 252, "joke": "President obama undergoes a lie detector test about the n-word usage: can we say the n-word?", "explanation": "TBD"},
    {"id": 253, "joke": "I didnt know he was going to fully commit to making me a human cannibal", "explanation": "TBD"},
    {"id": 254, "joke": "Call Donal Trump 'Big Donny'", "explanation": "TBD"},
    {"id": 255, "joke": "When dealing with models say 'those cloths are hideouge she'll have to take them off", "explanation": "TBD"},
    {"id": 256, "joke": "Dictatoership is a tatter ship", "explanation": "TBD"},
    {"id": 257, "joke": "Dont forget to UwU", "explanation": "TBD"},
    {"id": 258, "joke": "If you dont UwU I may break up", "explanation": "TBD"},
    {"id": 259, "joke": "Say 'it puts hair on your chest' and give t girl, it wont work", "explanation": "TBD"},
    {"id": 260, "joke": "If getting A's is not good enough to be liked by regular people its definitly not good enough to be liked by Ado the singer from one piece: RED", "explanation": "TBD"},
    {"id": 261, "joke": "The sublime song really say someone called the police but then the police end up killing them. RIP", "explanation": "TBD"},
    {"id": 262, "joke": "No one know that making metal music is called forging", "explanation": "TBD"},
    {"id": 263, "joke": "I was out racing cars again... with my human body... which is a lambo... or at least a BMW", "explanation": "TBD"},
    {"id": 264, "joke": "He went 1 fish 2 fish, I went 'oh god dam I need a tune sandwhich'", "explanation": "TBD"},
    {"id": 265, "joke": "Your mother should have given a footjob instead of had a baby", "explanation": "TBD"},
    {"id": 266, "joke": "Hbu is how about you. why is a b there?", "explanation": "TBD"},
    {"id": 267, "joke": "Abreviated machete: chete", "explanation": "TBD"},
    {"id": 268, "joke": "Are you even a gamer coder?", "explanation": "TBD"},
    {"id": 269, "joke": "Days list style: gamer coder gamer gamer coder gamer", "explanation": "TBD"},
    {"id": 270, "joke": "Hella weak", "explanation": "TBD"},
    {"id": 271, "joke": "Someone always reminds where milk comes from to ruin it", "explanation": "TBD"},
    {"id": 272, "joke": "Going in to only buy cakes: I need a cart", "explanation": "TBD"},
    {"id": 273, "joke": "Hecka is way worse", "explanation": "TBD"},
    {"id": 274, "joke": "When a single, who is standing, hears all the single ladies stand up song what do they do?", "explanation": ""},
    {"id": 275, "joke": "Purgatory waiting for the evevator", "explanation": "TBD"},
    {"id": 276, "joke": "How to make a million dollars by Ebeneezer Scrooge", "explanation": "TBD"}, 
    {"id": 277, "joke": "'and then i do me' uhh does that mean you are going to puke?", "explanation": "TBD"},
    {"id": 278, "joke": "Bean and cheese.. burger", "explanation": "TBD"},
    {"id": 279, "joke": "Eat hot cheeto before puke, red fountain technique", "explanation": "TBD"},
    {"id": 280, "joke": "Vr will some day help the blind to see! ...no it wont", "explanation": "TBD"},
    {"id": 281, "joke": "And then in the night he started quoting led zepplin but it wasnt the lyrics it was just stuff they had said", "explanation": "TBD"},
    {"id": 282, "joke": "About ACDC. I am joining this band fuck you all", "explanation": "TBD"},
    {"id": 283, "joke": "Eating these shrimps are like cunnalingus push up", "explanation": "TBD"},
    {"id": 284, "joke": "When I asked alexa to play ghetto music, she REALLY started playing mexican music", "explanation": "TBD"},
    {"id": 285, "joke": "LOTR mexican remake: 'lord of de grings'", "explanation": "TBD"},
    {"id": 286, "joke": "Halloween lets america scare rivals country", "explanation": "TBD"},
    {"id": 287, "joke": "Ohh its you again, i can tell by yout tits!", "explanation": "TBD"},
    {"id": 288, "joke": "I'm not giving blood unless its a girl in a nurse costume", "explanation": "TBD"},
    {"id": 289, "joke": "The flying spagetti monster probably has the best fucking pussy of the earth, ...the main threat to christianity has returned", "explanation": "TBD"},
    {"id": 290, "joke": "The -ets list: mark-et wall-et fag-et bass-et horn-et bask-et care-et rock-et and more", "explanation": "TBD"},
    {"id": 291, "joke": "Cinnebun repay tier: get them a cinnebun", "explanation": "TBD"},
    {"id": 292, "joke": "What did she want? im not sure, maybe buddas help or something", "explanation": "TBD"},
    {"id": 293, "joke": "Whores-ight gem stone", "explanation": "TBD"},
    {"id": 294, "joke": "Renegers joke: black people dont like it", "explanation": "TBD"},
    {"id": 295, "joke": "Asian accent: clinton eastwood", "explanation": "TBD"},
    {"id": 296, "joke": "The first indication of time travel event was the different price of gas", "explanation": "TBD"},
    {"id": 297, "joke": "The shins joke final form: in accent: shinmints", "explanation": "TBD"},
    {"id": 298, "joke": "To break up with your GF drop herr off at papa johns", "explanation": "TBD"},
    {"id": 299, "joke": "No one knows propaganda is 'properr gander' in east coast accent", "explanation": "TBD"}
]

# Initialize main window
root = tk.Tk()
root.title("Joke Randomizer")

# Define Tkinter variables after initializing root window
joke_text = tk.StringVar()
explanation_text = tk.StringVar()

last_joke_id = None

def get_random_joke():
    global last_joke_id
    joke = random.choice(jokes)
    last_joke_id = joke['id']
    joke_text.set(joke['joke'])
    explanation_text.set("")

def get_joke_explanation():
    global last_joke_id
    if last_joke_id is not None:
        joke = next((j for j in jokes if j["id"] == last_joke_id), None)
        if joke:
            explanation_text.set(joke['explanation'])
        else:
            messagebox.showerror("Error", "Explanation not found.")
    else:
        messagebox.showinfo("Info", "You need to get a joke first!")

# Load background image and resize
nft_image_path = "jokeGUI.png"  # Ensure jokeGUI.png is in the same directory as this script
bg_image = Image.open(nft_image_path)
bg_image = bg_image.resize((1000, 1000), Image.LANCZOS)  # Resize the image with LANCZOS filter
bg_image = ImageTk.PhotoImage(bg_image)

# Create a canvas and set the background
canvas = tk.Canvas(root, width=1000, height=1000)
canvas.pack(fill="both", expand=True)
canvas.create_image(0, 0, image=bg_image, anchor="nw")

# Joke label on the left
joke_label = tk.Label(root, textvariable=joke_text, wraplength=100, bg="white", fg="black", font=("Arial", 14))
joke_label_window = canvas.create_window(150, 200, window=joke_label, anchor="nw")

# Explanation label on the right
explanation_label = tk.Label(root, textvariable=explanation_text, wraplength=100, bg="white", fg="black", font=("Arial", 12))
explanation_label_window = canvas.create_window(850, 200, window=explanation_label, anchor="ne")

# "Tell a Joke" button
joke_button = tk.Button(root, text="Tell a Joke", command=get_random_joke, font=("Chafurin", 22), bg="black", fg="white")
joke_button_window = canvas.create_window(510, 780, window=joke_button, anchor="center")

# "Explanation" button
explanation_button = tk.Button(root, text="Explanation", command=get_joke_explanation, font=("Chafurin", 20), bg="black", fg="white")
explanation_button_window = canvas.create_window(510, 845, window=explanation_button, anchor="center")

# Start the main loop
root.mainloop()
